# Generated by Django 3.1.7 on 2021-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
