# Generated by Django 3.1.7 on 2021-04-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0004_auto_20210425_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
