# Generated by Django 3.1.7 on 2021-04-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0005_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_URL',
            field=models.URLField(default='static/img/No_image_available.png', null=True),
        ),
    ]
