# Generated by Django 3.1.7 on 2021-04-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0006_auto_20210425_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_URL',
            field=models.URLField(null=True),
        ),
    ]
