# Generated by Django 3.1.7 on 2021-04-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0007_auto_20210425_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
