# Generated by Django 3.1.7 on 2021-04-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0008_auto_20210425_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
