# Generated by Django 3.1.7 on 2021-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20210423_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cropping',
        ),
    ]
